Add uml diagram for retag, untag commands
AY2021S1-CS2103T-F12-1/tp pull request #322
Opened 2020-11-08 14:29 UTC by li-s

2020-11-08 15:28 UTC, anthony6401 commented on docs/DeveloperGuide.md
>  This command checks the presence of the `Tag` using `java.io.File.exists()`, and that the new tag name is unique, i.e. not present in the `AddressBook`.
I think this is incorrect. We don't use File.exists().

2020-11-09 01:49 UTC, luo-git requested changes
Need some small changes.😜

2020-11-09 01:49 UTC, luo-git commented on docs/DeveloperGuide.md
> +![LabelCommandSuccessExecution](images/LabelCommandSequenceDiagram.png)
Need to `<br>` or newline before the diagram.

2020-11-09 01:49 UTC, luo-git commented on docs/DeveloperGuide.md
> +![UntagCommandSuccessExecution](images/UntagSequenceDiagram.png)
Same as previous

2020-11-09 01:49 UTC, luo-git commented on docs/DeveloperGuide.md
> +![RetagCommandSuccessExecution](images/RetagSequenceDiagram.png)
Same as before.

2020-11-09 01:49 UTC, luo-git commented on docs/diagrams/LabelCommandSequenceDiagram.puml
> +
Add a line `destroy LabelCommand`

2020-11-09 01:49 UTC, luo-git commented on docs/diagrams/RetagSequenceDiagram.puml
> +
`destroy RetagCommand`

2020-11-09 01:49 UTC, luo-git commented on docs/diagrams/UntagSequenceDiagram.puml
> +deactivate UntagCommand
`destroy UntagCommand`

2020-11-09 03:12 UTC, luo-git approved these changes
Your approval rating has reached 100%.

2020-11-09 03:45 UTC, merged